name: pokedex
description: A new Flutter project.



publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 
  flutter_mobx: 
  get_it: ^3.1.0
  http: ^0.13.3
  cached_network_image:
  md2_tab_indicator: ^1.0.2
  provider:
  flutter_staggered_animations:
  sliding_sheet:
  flutter_icons:
  intl:
  simple_animations: ^1.3.6


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 
  build_runner: 

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball.png
    - assets/images/pokeball_dark.png
  
  fonts:
    - family: Google
      fonts:
        - asset: assets/fonts/ProductSans-Regular.ttf
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 700
  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
